[theme]
primaryColor="#7FDCC0"
backgroundColor="#F7FAF8"
secondaryBackgroundColor="#E9FBF3"
textColor="#083729"

[server]
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false
